In [54]:
import numpy as np
import pandas as pd

In [55]:
Philips_Financial_Cleaned_Data=pd.read_csv('C:/Users/arpit/OneDrive/Desktop/Philips/Fact_Inventory_Raw_Results.csv')
Philips_Financial_Cleaned_Data

,SKU_ID,Segment,Region,Unit_Cost_EUR,Average_Daily_Demand,Demand_Std_Dev,Expected_Lead_Time_Days,Actual_Lead_Time_Days,Lead_Time_Variance_Days,On_Hand_Inventory
0,PH-AED--1014,Connected Care,LATAM,4698.21,18.35,2.34,30,45,15,112
1,PH-AED--1018,Connected Care,APAC,40635.83,9.31,1.19,30,46,16,282
2,PH-AED--1021,Connected Care,EMEA,23884.44,8.92,1.53,30,43,13,51
3,PH-AED--1022,Connected Care,EMEA,14703.15,22.89,3.66,45,62,17,221
4,PH-AED--1027,Connected Care,EMEA,12599.10,6.02,2.08,30,28,-2,353
...,...,...,...,...,...,...,...,...,...,...
245,PH-VENT-1182,Connected Care,APAC,14492.32,24.93,5.15,30,35,5,88
246,PH-VENT-1198,Connected Care,APAC,35920.97,13.06,1.44,45,55,10,61
247,PH-VENT-1205,Connected Care,APAC,18084.34,10.83,2.34,30,41,11,274
248,PH-VENT-1239,Connected Care,EMEA,21723.22,18.66,1.94,45,60,15,117
249,PH-VENT-1240,Connected Care,APAC,41032.04,19.77,3.29,30,27,-3,213

#### Define a standard devation proxy for suppier lead time based on historical variations.
#### (Assuming a baseline historical standard deviation of 15% of the expected lead time)

In [56]:
Philips_Financial_Cleaned_Data['Lead_Time_Std_Dev']=Philips_Financial_Cleaned_Data['Expected_Lead_Time_Days']*0.15
Philips_Financial_Cleaned_Data

,SKU_ID,Segment,Region,Unit_Cost_EUR,Average_Daily_Demand,Demand_Std_Dev,Expected_Lead_Time_Days,Actual_Lead_Time_Days,Lead_Time_Variance_Days,On_Hand_Inventory,Lead_Time_Std_Dev
0,PH-AED--1014,Connected Care,LATAM,4698.21,18.35,2.34,30,45,15,112,4.50
1,PH-AED--1018,Connected Care,APAC,40635.83,9.31,1.19,30,46,16,282,4.50
2,PH-AED--1021,Connected Care,EMEA,23884.44,8.92,1.53,30,43,13,51,4.50
3,PH-AED--1022,Connected Care,EMEA,14703.15,22.89,3.66,45,62,17,221,6.75
4,PH-AED--1027,Connected Care,EMEA,12599.10,6.02,2.08,30,28,-2,353,4.50
...,...,...,...,...,...,...,...,...,...,...,...
245,PH-VENT-1182,Connected Care,APAC,14492.32,24.93,5.15,30,35,5,88,4.50
246,PH-VENT-1198,Connected Care,APAC,35920.97,13.06,1.44,45,55,10,61,6.75
247,PH-VENT-1205,Connected Care,APAC,18084.34,10.83,2.34,30,41,11,274,4.50
248,PH-VENT-1239,Connected Care,EMEA,21723.22,18.66,1.94,45,60,15,117,6.75
249,PH-VENT-1240,Connected Care,APAC,41032.04,19.77,3.29,30,27,-3,213,4.50

#### Calculate Optimal Safety Stock using the standard formula
#### Z = 1.96 represents a 95% service level requirement for Philips healthcare/consumer products

In [57]:
z=1.96
Philips_Financial_Cleaned_Data['Optimal_Safty_Stock']=np.sqrt((Philips_Financial_Cleaned_Data['Expected_Lead_Time_Days']*(Philips_Financial_Cleaned_Data['Demand_Std_Dev']**2))+((Philips_Financial_Cleaned_Data['Average_Daily_Demand']**2)*(Philips_Financial_Cleaned_Data['Lead_Time_Std_Dev']**2)))*z
Philips_Financial_Cleaned_Data

,SKU_ID,Segment,Region,Unit_Cost_EUR,Average_Daily_Demand,Demand_Std_Dev,Expected_Lead_Time_Days,Actual_Lead_Time_Days,Lead_Time_Variance_Days,On_Hand_Inventory,Lead_Time_Std_Dev,Optimal_Safty_Stock
0,PH-AED--1014,Connected Care,LATAM,4698.21,18.35,2.34,30,45,15,112,4.50,163.784930
1,PH-AED--1018,Connected Care,APAC,40635.83,9.31,1.19,30,46,16,282,4.50,83.102013
2,PH-AED--1021,Connected Care,EMEA,23884.44,8.92,1.53,30,43,13,51,4.50,80.370674
3,PH-AED--1022,Connected Care,EMEA,14703.15,22.89,3.66,45,62,17,221,6.75,306.634277
4,PH-AED--1027,Connected Care,EMEA,12599.10,6.02,2.08,30,28,-2,353,4.50,57.600665
...,...,...,...,...,...,...,...,...,...,...,...,...
245,PH-VENT-1182,Connected Care,APAC,14492.32,24.93,5.15,30,35,5,88,4.50,226.726758
246,PH-VENT-1198,Connected Care,APAC,35920.97,13.06,1.44,45,55,10,61,6.75,173.818034
247,PH-VENT-1205,Connected Care,APAC,18084.34,10.83,2.34,30,41,11,274,4.50,98.768603
248,PH-VENT-1239,Connected Care,EMEA,21723.22,18.66,1.94,45,60,15,117,6.75,248.186032
249,PH-VENT-1240,Connected Care,APAC,41032.04,19.77,3.29,30,27,-3,213,4.50,177.912453

In [58]:
Philips_Financial_Cleaned_Data['Optimal_Safety_Stock']=Philips_Financial_Cleaned_Data['Optimal_Safty_Stock'].round(0).astype(int)
Philips_Financial_Cleaned_Data

,SKU_ID,Segment,Region,Unit_Cost_EUR,Average_Daily_Demand,Demand_Std_Dev,Expected_Lead_Time_Days,Actual_Lead_Time_Days,Lead_Time_Variance_Days,On_Hand_Inventory,Lead_Time_Std_Dev,Optimal_Safty_Stock,Optimal_Safety_Stock
0,PH-AED--1014,Connected Care,LATAM,4698.21,18.35,2.34,30,45,15,112,4.50,163.784930,164
1,PH-AED--1018,Connected Care,APAC,40635.83,9.31,1.19,30,46,16,282,4.50,83.102013,83
2,PH-AED--1021,Connected Care,EMEA,23884.44,8.92,1.53,30,43,13,51,4.50,80.370674,80
3,PH-AED--1022,Connected Care,EMEA,14703.15,22.89,3.66,45,62,17,221,6.75,306.634277,307
4,PH-AED--1027,Connected Care,EMEA,12599.10,6.02,2.08,30,28,-2,353,4.50,57.600665,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,PH-VENT-1182,Connected Care,APAC,14492.32,24.93,5.15,30,35,5,88,4.50,226.726758,227
246,PH-VENT-1198,Connected Care,APAC,35920.97,13.06,1.44,45,55,10,61,6.75,173.818034,174
247,PH-VENT-1205,Connected Care,APAC,18084.34,10.83,2.34,30,41,11,274,4.50,98.768603,99
248,PH-VENT-1239,Connected Care,EMEA,21723.22,18.66,1.94,45,60,15,117,6.75,248.186032,248
249,PH-VENT-1240,Connected Care,APAC,41032.04,19.77,3.29,30,27,-3,213,4.50,177.912453,178

#### Calculate Current Value and Actual Carrying Cost (WACC + Storage = 22%)

In [59]:
Philips_Financial_Cleaned_Data['Current_Inventory_Value_EUR']=Philips_Financial_Cleaned_Data['On_Hand_Inventory']*Philips_Financial_Cleaned_Data['Unit_Cost_EUR']
Philips_Financial_Cleaned_Data['Annual_Carrying_COst_EUR']=Philips_Financial_Cleaned_Data['Current_Inventory_Value_EUR']*0.22
Philips_Financial_Cleaned_Data

,SKU_ID,Segment,Region,Unit_Cost_EUR,Average_Daily_Demand,Demand_Std_Dev,Expected_Lead_Time_Days,Actual_Lead_Time_Days,Lead_Time_Variance_Days,On_Hand_Inventory,Lead_Time_Std_Dev,Optimal_Safty_Stock,Optimal_Safety_Stock,Current_Inventory_Value_EUR,Annual_Carrying_COst_EUR
0,PH-AED--1014,Connected Care,LATAM,4698.21,18.35,2.34,30,45,15,112,4.50,163.784930,164,526199.52,1.157639e+05
1,PH-AED--1018,Connected Care,APAC,40635.83,9.31,1.19,30,46,16,282,4.50,83.102013,83,11459304.06,2.521047e+06
2,PH-AED--1021,Connected Care,EMEA,23884.44,8.92,1.53,30,43,13,51,4.50,80.370674,80,1218106.44,2.679834e+05
3,PH-AED--1022,Connected Care,EMEA,14703.15,22.89,3.66,45,62,17,221,6.75,306.634277,307,3249396.15,7.148672e+05
4,PH-AED--1027,Connected Care,EMEA,12599.10,6.02,2.08,30,28,-2,353,4.50,57.600665,58,4447482.30,9.784461e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,PH-VENT-1182,Connected Care,APAC,14492.32,24.93,5.15,30,35,5,88,4.50,226.726758,227,1275324.16,2.805713e+05
246,PH-VENT-1198,Connected Care,APAC,35920.97,13.06,1.44,45,55,10,61,6.75,173.818034,174,2191179.17,4.820594e+05
247,PH-VENT-1205,Connected Care,APAC,18084.34,10.83,2.34,30,41,11,274,4.50,98.768603,99,4955109.16,1.090124e+06
248,PH-VENT-1239,Connected Care,EMEA,21723.22,18.66,1.94,45,60,15,117,6.75,248.186032,248,2541616.74,5.591557e+05
249,PH-VENT-1240,Connected Care,APAC,41032.04,19.77,3.29,30,27,-3,213,4.50,177.912453,178,8739824.52,1.922761e+06

#### Flag SKUs that are overstocked vs understocked

In [60]:
Philips_Financial_Cleaned_Data['Inventory_Status']=np.where(Philips_Financial_Cleaned_Data['On_Hand_Inventory']<Philips_Financial_Cleaned_Data['Optimal_Safety_Stock'],'Understocked / Risk',np.where(Philips_Financial_Cleaned_Data['On_Hand_Inventory']>(Philips_Financial_Cleaned_Data['Optimal_Safety_Stock']*2),'Overstocked / Excess Capital','Optimal'))
Philips_Financial_Cleaned_Data

,SKU_ID,Segment,Region,Unit_Cost_EUR,Average_Daily_Demand,Demand_Std_Dev,Expected_Lead_Time_Days,Actual_Lead_Time_Days,Lead_Time_Variance_Days,On_Hand_Inventory,Lead_Time_Std_Dev,Optimal_Safty_Stock,Optimal_Safety_Stock,Current_Inventory_Value_EUR,Annual_Carrying_COst_EUR,Inventory_Status
0,PH-AED--1014,Connected Care,LATAM,4698.21,18.35,2.34,30,45,15,112,4.50,163.784930,164,526199.52,1.157639e+05,Understocked / Risk
1,PH-AED--1018,Connected Care,APAC,40635.83,9.31,1.19,30,46,16,282,4.50,83.102013,83,11459304.06,2.521047e+06,Overstocked / Excess Capital
2,PH-AED--1021,Connected Care,EMEA,23884.44,8.92,1.53,30,43,13,51,4.50,80.370674,80,1218106.44,2.679834e+05,Understocked / Risk
3,PH-AED--1022,Connected Care,EMEA,14703.15,22.89,3.66,45,62,17,221,6.75,306.634277,307,3249396.15,7.148672e+05,Understocked / Risk
4,PH-AED--1027,Connected Care,EMEA,12599.10,6.02,2.08,30,28,-2,353,4.50,57.600665,58,4447482.30,9.784461e+05,Overstocked / Excess Capital
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,PH-VENT-1182,Connected Care,APAC,14492.32,24.93,5.15,30,35,5,88,4.50,226.726758,227,1275324.16,2.805713e+05,Understocked / Risk
246,PH-VENT-1198,Connected Care,APAC,35920.97,13.06,1.44,45,55,10,61,6.75,173.818034,174,2191179.17,4.820594e+05,Understocked / Risk
247,PH-VENT-1205,Connected Care,APAC,18084.34,10.83,2.34,30,41,11,274,4.50,98.768603,99,4955109.16,1.090124e+06,Overstocked / Excess Capital
248,PH-VENT-1239,Connected Care,EMEA,21723.22,18.66,1.94,45,60,15,117,6.75,248.186032,248,2541616.74,5.591557e+05,Understocked / Risk
249,PH-VENT-1240,Connected Care,APAC,41032.04,19.77,3.29,30,27,-3,213,4.50,177.912453,178,8739824.52,1.922761e+06,Optimal

In [61]:
Philips_Financial_Cleaned_Data.to_csv('C:/Users/arpit/OneDrive/Desktop/Philips/Philips optimized inventory metrics.csv',index=False)